<?php

//get_header();

//if (have_posts()) : while (have_posts()) : the_post();
include("header.php");
?>
<main role="main">
    <section class="bg-primary py-5" id="cabecalho">
        <div class="container py-lg-4 text-center text-white">
            <h1 class=" fw-light"><i>POLÍTICA DE <b class="fw-bold">PRIVACIDADE</b></i></h1>
        </div>
    </section>
    <section class="py-5">
        <div class="container py-lg-5">
            <article>
                <h2>1 . Informações gerais e definições</h2>
                <p>
                Estamos comprometidos em proteger o direito de privacidade quando do tratamento de dados pessoais. Neste sentido, a presente Política de Privacidade traz definições, informações sobre coleta e tratamento de dados pessoais, informações referentes à segurança dos dados pessoais tratados, assim como, demais informações pertinentes ao assunto em questão. Abaixo, seguem definições de termos técnicos utilizados na presente Política, de acordo com a Lei Geral de Proteção de Dados, a fim de facilitar o entendimento do leitor: “LGPD” – Lei nº 13.709/2018, conhecida como Lei Geral de Proteção de Dados; “Dado Pessoal” – informação relativa à pessoa identificada ou identificável; “Dado Pessoal Sensível” – dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou à organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; “Tratamento” – toda operação realizada com dados pessoais, como as que se referem à coleta, produção, classificação, utilização, acesso, armazenamento, eliminação, transferência, difusão, etc. “Anonimização” – utilização de meios técnicos razoáveis e disponíveis no momento do tratamento para impossibilitar a associação do dado a um indivíduo; “Titular” – pessoa a quem se refere o dado pessoal objeto de tratamento; “Controlador” – pessoa natural ou jurídica, de direito público ou privado, a quem compete as decisões referentes ao tratamento de dados pessoais; “Encarregado” – pessoa indicada para atuar como canal de comunicação entre os titulares dos dados, o controlador e a Autoridade Nacional de Proteção de Dados (ANPD); “ANPD” – órgão da administração pública responsável por zelar, implementar e fiscalizar o cumprimento desta Lei no território nacional; Demais conceitos importantes para a correta compreensão da presente Política de Privacidade e Segurança podem ser verificados no próprio texto legal da LGPD.
                </p>
                <h2>1 . Informações gerais e definições</h2>
                <p>
                Estamos comprometidos em proteger o direito de privacidade quando do tratamento de dados pessoais. Neste sentido, a presente Política de Privacidade traz definições, informações sobre coleta e tratamento de dados pessoais, informações referentes à segurança dos dados pessoais tratados, assim como, demais informações pertinentes ao assunto em questão. Abaixo, seguem definições de termos técnicos utilizados na presente Política, de acordo com a Lei Geral de Proteção de Dados, a fim de facilitar o entendimento do leitor: “LGPD” – Lei nº 13.709/2018, conhecida como Lei Geral de Proteção de Dados; “Dado Pessoal” – informação relativa à pessoa identificada ou identificável; “Dado Pessoal Sensível” – dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou à organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; “Tratamento” – toda operação realizada com dados pessoais, como as que se referem à coleta, produção, classificação, utilização, acesso, armazenamento, eliminação, transferência, difusão, etc. “Anonimização” – utilização de meios técnicos razoáveis e disponíveis no momento do tratamento para impossibilitar a associação do dado a um indivíduo; “Titular” – pessoa a quem se refere o dado pessoal objeto de tratamento; “Controlador” – pessoa natural ou jurídica, de direito público ou privado, a quem compete as decisões referentes ao tratamento de dados pessoais; “Encarregado” – pessoa indicada para atuar como canal de comunicação entre os titulares dos dados, o controlador e a Autoridade Nacional de Proteção de Dados (ANPD); “ANPD” – órgão da administração pública responsável por zelar, implementar e fiscalizar o cumprimento desta Lei no território nacional; Demais conceitos importantes para a correta compreensão da presente Política de Privacidade e Segurança podem ser verificados no próprio texto legal da LGPD.
                </p>
                <h2>1 . Informações gerais e definições</h2>
                <p>
                Estamos comprometidos em proteger o direito de privacidade quando do tratamento de dados pessoais. Neste sentido, a presente Política de Privacidade traz definições, informações sobre coleta e tratamento de dados pessoais, informações referentes à segurança dos dados pessoais tratados, assim como, demais informações pertinentes ao assunto em questão. Abaixo, seguem definições de termos técnicos utilizados na presente Política, de acordo com a Lei Geral de Proteção de Dados, a fim de facilitar o entendimento do leitor: “LGPD” – Lei nº 13.709/2018, conhecida como Lei Geral de Proteção de Dados; “Dado Pessoal” – informação relativa à pessoa identificada ou identificável; “Dado Pessoal Sensível” – dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou à organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; “Tratamento” – toda operação realizada com dados pessoais, como as que se referem à coleta, produção, classificação, utilização, acesso, armazenamento, eliminação, transferência, difusão, etc. “Anonimização” – utilização de meios técnicos razoáveis e disponíveis no momento do tratamento para impossibilitar a associação do dado a um indivíduo; “Titular” – pessoa a quem se refere o dado pessoal objeto de tratamento; “Controlador” – pessoa natural ou jurídica, de direito público ou privado, a quem compete as decisões referentes ao tratamento de dados pessoais; “Encarregado” – pessoa indicada para atuar como canal de comunicação entre os titulares dos dados, o controlador e a Autoridade Nacional de Proteção de Dados (ANPD); “ANPD” – órgão da administração pública responsável por zelar, implementar e fiscalizar o cumprimento desta Lei no território nacional; Demais conceitos importantes para a correta compreensão da presente Política de Privacidade e Segurança podem ser verificados no próprio texto legal da LGPD.
                </p>
                <h2>1 . Informações gerais e definições</h2>
                <p>
                Estamos comprometidos em proteger o direito de privacidade quando do tratamento de dados pessoais. Neste sentido, a presente Política de Privacidade traz definições, informações sobre coleta e tratamento de dados pessoais, informações referentes à segurança dos dados pessoais tratados, assim como, demais informações pertinentes ao assunto em questão. Abaixo, seguem definições de termos técnicos utilizados na presente Política, de acordo com a Lei Geral de Proteção de Dados, a fim de facilitar o entendimento do leitor: “LGPD” – Lei nº 13.709/2018, conhecida como Lei Geral de Proteção de Dados; “Dado Pessoal” – informação relativa à pessoa identificada ou identificável; “Dado Pessoal Sensível” – dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou à organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; “Tratamento” – toda operação realizada com dados pessoais, como as que se referem à coleta, produção, classificação, utilização, acesso, armazenamento, eliminação, transferência, difusão, etc. “Anonimização” – utilização de meios técnicos razoáveis e disponíveis no momento do tratamento para impossibilitar a associação do dado a um indivíduo; “Titular” – pessoa a quem se refere o dado pessoal objeto de tratamento; “Controlador” – pessoa natural ou jurídica, de direito público ou privado, a quem compete as decisões referentes ao tratamento de dados pessoais; “Encarregado” – pessoa indicada para atuar como canal de comunicação entre os titulares dos dados, o controlador e a Autoridade Nacional de Proteção de Dados (ANPD); “ANPD” – órgão da administração pública responsável por zelar, implementar e fiscalizar o cumprimento desta Lei no território nacional; Demais conceitos importantes para a correta compreensão da presente Política de Privacidade e Segurança podem ser verificados no próprio texto legal da LGPD.
                </p>
            </article>
        </div>
    </section>

</main>
<?php
include("footer.php");
//endwhile; 
//endif; 
//get_footer();
?>